services:
  redis:
    image: redis
    container_name: redis_server
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_app
    ports:
      - "8080:8080"
    depends_on:
      redis:
        condition: service_healthy
    env_file:
      - .env